### ISSUE TITLE
ValueError: api query returns no item for pattern {'name': 'clara_pt_spleen_ct_segmentation_1'}

### ISSUE THREAD

**Issue by Zrrr1997** [diazandr3s/MONAILabel-Apps#8]
Hi there,

I have been using the original repo to play around with the sample apps, but I also wanted to try out [BIFSeg](https://arxiv.org/abs/1710.04043) to see how it works. 

I am having trouble running the `segmentation_spleen_scribbles` app. I installed all dependencies from the `requirements.txt` but am not stumbling upon this error:

```
(monai_apps) zrrr@my_pc:~/repos/apps_monai/MONAILabel-Apps$ CUDA_VISIBLE_DEVICES=0 monailabel start_server --app /home/zmarinov/repos/apps_monai/MONAILabel-Apps/segmentation_spleen_scribbles/ --studies /home/zmarinov/repos/MONAI_Label/MONAILabel/datasets/Task09_Spleen/imagesTr/
Using PYTHONPATH=/home/zmarinov/repos/apps_monai/MONAILabel-Apps:/cvhci/software/deeplearn/caffe/build_gpu/install/python:
[2022-05-13 10:27:06,733] [5867] [MainThread] [INFO] (__main__:293) - USING:: app = /home/zmarinov/repos/apps_monai/MONAILabel-Apps/segmentation_spleen_scribbles
[2022-05-13 10:27:06,733] [5867] [MainThread] [INFO] (__main__:293) - USING:: studies = /home/zmarinov/repos/MONAI_Label/MONAILabel/datasets/Task09_Spleen/imagesTr
[2022-05-13 10:27:06,733] [5867] [MainThread] [INFO] (__main__:293) - USING:: verbose = INFO
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: conf = None
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: host = 0.0.0.0
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: port = 8000
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: uvicorn_app = monailabel.app:app
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: ssl_keyfile = None
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: ssl_certfile = None
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: ssl_keyfile_password = None
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: ssl_ca_certs = None
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: workers = 1
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: limit_concurrency = None
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: access_log = False
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: log_config = None
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: dryrun = False
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:293) - USING:: action = start_server
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_API_STR = 
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_PROJECT_NAME = MONAILabel
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_APP_DIR = 
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_STUDIES = 
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_APP_CONF = '{}'
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_USERNAME = 
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_PASSWORD = 
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_CACHE_PATH = 
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_QIDO_PREFIX = 
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_WADO_PREFIX = 
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_STOW_PREFIX = 
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_DICOMWEB_FETCH_BY_FRAME = False
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_DATASTORE_AUTO_RELOAD = True
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_DATASTORE_FILE_EXT = '["*.nii.gz", "*.nii", "*.nrrd"]'
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_SERVER_PORT = 8000
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_CORS_ORIGINS = '[]'
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_SESSION_PATH = 
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_SESSION_EXPIRY = 3600
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_INFER_CONCURRENCY = -1
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:297) - ENV SETTINGS:: MONAI_LABEL_INFER_TIMEOUT = 600
[2022-05-13 10:27:06,734] [5867] [MainThread] [INFO] (__main__:298) - 
[2022-05-13 10:27:07,785] [5867] [MainThread] [INFO] (uvicorn.error:82) - Started server process [5867]
[2022-05-13 10:27:07,786] [5867] [MainThread] [INFO] (uvicorn.error:45) - Waiting for application startup.
[2022-05-13 10:27:07,786] [5867] [MainThread] [INFO] (monailabel.interfaces.utils.app:38) - Initializing App from: /home/zmarinov/repos/apps_monai/MONAILabel-Apps/segmentation_spleen_scribbles; studies: /home/zmarinov/repos/MONAI_Label/MONAILabel/datasets/Task09_Spleen/imagesTr; conf: {}
[2022-05-13 10:27:07,808] [5867] [MainThread] [INFO] (monailabel.utils.others.class_utils:35) - Subclass for MONAILabelApp Found: <class 'main.MyApp'>
[2022-05-13 10:27:07,808] [5867] [MainThread] [INFO] (main:46) - TTA Enabled: 0; Samples: 5
[2022-05-13 10:27:07,808] [5867] [MainThread] [INFO] (monailabel.interfaces.app:121) - Init Datastore for: /home/zmarinov/repos/MONAI_Label/MONAILabel/datasets/Task09_Spleen/imagesTr
[2022-05-13 10:27:07,808] [5867] [MainThread] [INFO] (monailabel.datastore.local:125) - Auto Reload: True; Extensions: ['*.nii.gz', '*.nii', '*.nrrd']
[2022-05-13 10:27:07,835] [5867] [MainThread] [INFO] (monailabel.datastore.local:538) - Invalidate count: 0
[2022-05-13 10:27:07,835] [5867] [MainThread] [INFO] (monailabel.datastore.local:145) - Start observing external modifications on datastore (AUTO RELOAD)
[2022-05-13 10:27:09,353] [5867] [MainThread] [ERROR] (uvicorn.error:119) - Traceback (most recent call last):
  File "/home/zmarinov/repos/apps_monai/MONAILabel-Apps/monai_apps/lib/python3.8/site-packages/starlette/routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "/home/zmarinov/repos/apps_monai/MONAILabel-Apps/monai_apps/lib/python3.8/site-packages/starlette/routing.py", line 518, in __aenter__
    await self._router.startup()
  File "/home/zmarinov/repos/apps_monai/MONAILabel-Apps/monai_apps/lib/python3.8/site-packages/starlette/routing.py", line 598, in startup
    await handler()
  File "/home/zmarinov/repos/apps_monai/MONAILabel-Apps/monai_apps/lib/python3.8/site-packages/monailabel/app.py", line 99, in startup_event
    instance = app_instance()
  File "/home/zmarinov/repos/apps_monai/MONAILabel-Apps/monai_apps/lib/python3.8/site-packages/monailabel/interfaces/utils/app.py", line 51, in app_instance
    app = c(app_dir=app_dir, studies=studies, conf=conf)
  File "/home/zmarinov/repos/apps_monai/MONAILabel-Apps/segmentation_spleen_scribbles/main.py", line 49, in __init__
    super().__init__(
  File "/home/zmarinov/repos/apps_monai/MONAILabel-Apps/monai_apps/lib/python3.8/site-packages/monailabel/interfaces/app.py", line 87, in __init__
    self._infers = self.init_infers()
  File "/home/zmarinov/repos/apps_monai/MONAILabel-Apps/segmentation_spleen_scribbles/main.py", line 61, in init_infers
    self.final_model, load_from_mmar(self.mmar, self.model_dir)
  File "/home/zmarinov/repos/apps_monai/MONAILabel-Apps/monai_apps/lib/python3.8/site-packages/monai/apps/mmars/mmars.py", line 226, in load_from_mmar
    model_dir = download_mmar(item=item, mmar_dir=mmar_dir, progress=progress, version=version, api=api)
  File "/home/zmarinov/repos/apps_monai/MONAILabel-Apps/monai_apps/lib/python3.8/site-packages/monai/apps/mmars/mmars.py", line 143, in download_mmar
    raise ValueError(f"api query returns no item for pattern {item}.  Please change or shorten it.")
ValueError: api query returns no item for pattern {'name': 'clara_pt_spleen_ct_segmentation_1'}.  Please change or shorten it.

[2022-05-13 10:27:09,354] [5867] [MainThread] [ERROR] (uvicorn.error:56) - Application startup failed. Exiting.
```

I am just using the `datasets/Task09_Spleen/imagesTr` directory from the [original MONAILabel repo](https://github.com/Project-MONAI/MONAILabel).

As far as I can understand the stack trace, the model cannot be downloaded from the Medical Model Archive (MMAR), right? I am not quite sure why the model cannot be downloaded. Can anyone give any hints? 

P.S. The [example from the docs](https://docs.monai.io/en/stable/apps.html?highlight=mmar#monai.apps.load_from_mmar) for using `load_from_mmar` gives me the same error for the` prostate_mri` model

**Comment by Zrrr1997** [comment]
Strangely, removing the `_1` suffix in both cases solves the compilation error, e.g., `clara_pt_spleen_ct_segmentation` instead of `clara_pt_spleen_ct_segmentation_1`. I am still not quite sure if that is the same model, though. 

Leaving this in case someone runs into the same issue. It would be great if you could confirm that this is a valid solution, though. Should we also link it to the main MONAILabel repo if you think that it is relevant?

**Comment by diazandr3s** [comment]
Thanks for highlighting this, @Zrrr1997.

It is the same model. Those weights are downloaded from the NVIDIA NGC: https://catalog.ngc.nvidia.com/models?filters=&orderBy=dateModifiedDESC&query=clara_pt_spleen_ct_segmentation

This repo is more to show applications to different image modalities. The main MONAI Label repo has all that you can find here.

Thanks again!

**Comment by diazandr3s** [comment]
Fix proposed here https://github.com/diazandr3s/MONAILabel-Apps/pull/9

**Comment by SachidanandAlle** [comment]
I suggest to use main branch or weekly packages or latest monailabel docker..

**Comment by masadcv** [comment]
@Zrrr1997 please correct me if I am wrong - I believe @Zrrr1997 wants to look into scribbles method that use output from CNN in addition to scribbles for optimisation. Possibly that's why an interest in BIFSeg that does this. The MONAI main repo does not show this functionality.
